<a href="https://colab.research.google.com/github/varunpenumudi/notes/blob/master/Pytorch_codemy/Pytorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
np.random.rand(3, 4)
np.zeros(3).dtype

dtype('float64')

In [3]:
import torch

# Tensor
- MultiDimensional Arrays
- Little Bit More Powerful than numpy arrays
- Suitable for GPU's

In [4]:
torch.randn(3, 4)

tensor([[-0.5605,  0.3500,  0.2978, -1.2368],
        [ 0.6572,  0.4685,  0.3688, -0.2006],
        [-1.2895,  0.5473, -0.8969,  0.8785]])

In [5]:
torch.ones(3, 4, 2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [6]:
torch.tensor([[1, 0], [0, 1]])

tensor([[1, 0],
        [0, 1]])

In [7]:
np1 = np.random.rand(4)
print(np1)
torch.tensor(np1)

[0.76925315 0.01560535 0.45355679 0.03187684]


tensor([0.7693, 0.0156, 0.4536, 0.0319], dtype=torch.float64)

In [8]:
torch.tensor([0.0, 1.1, 2.2]).dtype

torch.float32

# Reshape and slice

## Reshape

Reshape the array into rows and cols size

- `tensor.reshape(row, cols)`
- `tensor.reshape(row, -1)` only rows
- `tensor.reshape(-1, cols)` only cols

In [9]:
#tsr = torch.tensor(np.arange(10))
tsr = torch.arange(10)
tsr

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# reshape to 10*1
tsr.reshape(10, -1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [11]:
tsr.reshape(5, -1) #reshape to 5 rows

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [12]:
tsr.reshape(-1, 5) # reshape to 5 cols

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
tsr.reshape(2, 5)
# cannot work
# tsr.reshape(2, 6)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## View
- view is same as reshape

In [14]:
tsr.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

## Indexing and Slicing

In [15]:
t1 = torch.rand(3, 5)
t1

tensor([[0.0468, 0.4265, 0.9733, 0.4536, 0.3531],
        [0.6586, 0.2995, 0.1959, 0.4661, 0.3824],
        [0.5473, 0.0348, 0.2845, 0.2490, 0.7294]])

In [16]:
t1[1:3] # second and thrid rows

tensor([[0.6586, 0.2995, 0.1959, 0.4661, 0.3824],
        [0.5473, 0.0348, 0.2845, 0.2490, 0.7294]])

In [17]:
t1[:, 1] # second col in all rows

tensor([0.4265, 0.2995, 0.0348])

In [18]:
t1[:, 1:2] # second col in all rows as rows*1 vector

tensor([[0.4265],
        [0.2995],
        [0.0348]])

In [19]:
t1[1:3, 1:3]

tensor([[0.2995, 0.1959],
        [0.0348, 0.2845]])

# Tensor Math Operations
- +,-,/,%,*
- Reassignment

In [20]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([6,7,8,9,10])
a+b

tensor([ 7,  9, 11, 13, 15])

In [21]:
# addition
r1 = a+b
r2 = torch.add(a,b)
print(r1, r2)

tensor([ 7,  9, 11, 13, 15]) tensor([ 7,  9, 11, 13, 15])


In [22]:
# subtraction
r1 = a-b
r2 = torch.sub(a,b)
print(r1, r2)

tensor([-5, -5, -5, -5, -5]) tensor([-5, -5, -5, -5, -5])


In [23]:
# multiply
r1 = a*b
r2 = torch.mul(a,b)
print(r1, r2)

tensor([ 6, 14, 24, 36, 50]) tensor([ 6, 14, 24, 36, 50])


In [24]:
# division
r1 = a/b
r2 = torch.div(a,b)
print(r1, r2)

tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000]) tensor([0.1667, 0.2857, 0.3750, 0.4444, 0.5000])


In [25]:
# remainder
r1 = a%b
r2 = torch.remainder(a,b)
print(r1, r2)

tensor([1, 2, 3, 4, 5]) tensor([1, 2, 3, 4, 5])


In [28]:
 # Pow
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([2,2,2,0.5, 2])

a**b
torch.pow(a,b)

tensor([ 1.,  4.,  9.,  2., 25.])

In [27]:
# SHORTHAND
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([6,7,8,9,10])
a.add_(b)

tensor([ 7,  9, 11, 13, 15])